import { Lora } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { Metadata } from "next";

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "nate's job board",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lora.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
